CHALLENGE_LENGTH = 4
CHALLENGE_STRING = "authClient"
SERVER_IP = "127.0.0.1"
SERVER_PORT = 65432
INVALID_CHALLENGE_MESSAGE_0 = "INVALID_CHALLENGE_RESPONSE"
REQUEST_TO_PRINT_QUOTE_MESSAGE = "RequestToPrintQuote"
INVALID_CHALLENGE_MESSAGE_1 = "STRING_DOESNOT_CONTAIN_ORIGINAL_CHALLENGE"